<script type="text/javascript">
    //<![CDATA[
    function importProduct() {
        new Ajax.Request('<?php echo $this->getAjaxCheckUrl() ?>', {
            method:     'get',
            onSuccess: function(transport){
                if (transport.responseText){
                    alert(transport.responseText)
                }
            }
        });
    }

    var enable=document.getElementById("rock_product_import_configuration_rock_product_import_general_enabled");
    var importButtonRow=document.getElementById("row_rock_product_import_configuration_rock_product_import_general_import");

    if(enable.value==1){
        importButtonRow.style.display='';
    }
    else{
        importButtonRow.style.display='none';
    }

    document.getElementById("rock_product_import_configuration_rock_product_import_general_enabled").onchange = function() {
        if(enable.value==1){
            importButtonRow.style.display='';
        }
        else{
            importButtonRow.style.display='none';
        }
    }

    //]]>
</script>

<?php echo $this->getButtonHtml() ?>

<!-- <script src="http://code.jquery.com/jquery-latest.js"></script>
<script>
 $(document).ready(function(){
     setInterval(ajaxcall, 1000);
 });
 function importProduct(){
     $.ajax({
         url: '<?php //echo $this->getAjaxCheckUrl() ?>',
         success: function(data) {
             data = data.split(':');
             $('#hours').html(data[0]);
             $('#minutes').html(data[1]);
             $('#seconds').html(data[2]);
         }
     });
 }
</script>
<span id="hours">0</span>:<span id="minutes">0</span>:<span id="seconds">0</span> -->