<?php
// Setting variables
$_product = $this->getProduct();
?>

<?php if ($_product->isSaleable()): ?>
    <?php if (!$this->isHideAddToQuoteButton()): ?>
        <button type="button" title="<?php echo Mage::helper('qquoteadv')->__("Add to Quote"); ?>"
                class="button btn-cart btn-quote" onclick="<?php echo $this->getActionQuote(); ?>">
            <span><span><?php echo Mage::helper('qquoteadv')->__("Add to Quote"); ?></span></span></button>
    <?php endif; ?>
<?php else: ?>
    <div class="add-to-cart">
        <?php if (!$this->isHideAddToQuoteButton()): ?>
            <?php if (!$_product->isGrouped() && (!$_product->isSaleable() || $this->isHideAddToCartButton() === true)): ?>
                <div class="qty-wrapper">
                    <label for="qty"><?php echo $this->__('Qty:'); ?></label>
                    <input type="text" name="qty" id="qty" maxlength="12"
                           value="<?php echo $this->getProductDefaultQty() * 1 ?>"
                           title="<?php echo $this->__('Qty') ?>" class="input-text qty"/>
                </div>
            <?php endif; ?>
            <div class="add-to-cart-buttons">
                <button type="button" title="<?php echo Mage::helper('qquoteadv')->__("Add to Quote"); ?>"
                        class="button btn-cart btn-quote" onclick="<?php echo $this->getActionQuote(); ?>">
                    <span><span><?php echo Mage::helper('qquoteadv')->__("Add to Quote"); ?></span></span></button>
            </div>
        <?php endif; ?>
    </div>
<?php endif; ?>
