<?php $hideAddToCartButton = Mage::getConfig()->getModuleConfig('Ophirah_Not2Order')->is('active', 'true') && $this->getProduct()->getData('quotemode_conditions') > 0 ? Mage::helper('not2order')->autoHideCartButton(Mage::helper('qquoteadv')->hideQuoteButton($this->getProduct())) : false; ?>
<?php $_product = $this->getProduct();?>
<?php $buttonTitle = $this->__('Add to Cart'); ?>
<div class="add-to-cart">
    <?php if (!$_product->isGrouped() && $_product->isSaleable() && $hideAddToCartButton === false): ?>
        <div class="qty-wrapper">
            <label for="qty"><?php echo $this->__('Qty:') ?></label>
            <input type="text" pattern="\d*" name="qty" id="qty" maxlength="12" value="<?php echo max($this->getProductDefaultQty() * 1, 1) ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty"/>
        </div>
    <?php endif; ?>
    <div class="add-to-cart-buttons">
        <button type="button" title="<?php echo $buttonTitle ?>" class="button btn-cart" onclick="productAddToCartForm.submit(this)"><span><span><?php echo $buttonTitle ?></span></span> </button>
        <?php echo $this->getChildHtml('', true, true) ?>
    </div>
</div>



