<div class="entry-edit">
    <div class="content-header">
        <table cellspacing="0" class="grid-header">
            <tr>
                <td><h3><?php echo $this->getTitle(); ?></h3></td>
                <td align="right">
                    <button onclick="setLocation('<?php echo $this->getBackUrl(); ?>');" class="scalable back" type="button"><span><?php echo $this->__('Back') ?></span></button>
                    <button onclick="document.location.href='<?php echo $this->getDeleteUrl() ?>'" class="scalable delete" type="button"><span><?php echo $this->__('Delete') ?></span></button>
                    <button onclick="priorityForm.submit();" class="scalable save" type="button"><span><?php echo $this->__('Save'); ?></span></button>
                </td>
            </tr>
        </table>
    </div>

    <form id="priority_form" method="POST" name="priority_form" action="<?php echo $this->getUrl("*/*/Save"); ?>">
        <div>
            <input type="hidden" id="form_key" name="form_key"  value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
            <input type="hidden" id="ctp_id" name="ctp_id"  value="<?php echo $this->getPriority()->getId() ?>" />
        </div>
        <div id="ticket_fieldset" class="fieldset ">
            <div class="hor-scroll">
                <table class="form-list" cellspacing="0">
                    <tbody>
                        <tr>
                            <td class="label"><?php echo $this->__('Name'); ?> <span class="required">*</span></td>
                            <td class="value">
                                <input class="input-text required-entry" type="text" name="priority[ctp_name]" id="ctp_name" value="<?php echo $this->getPriority()->getctp_name(); ?>"></input>
                            </td>
                        </tr>
                        <tr>
                            <td class="label"><?php echo $this->__('Priority value'); ?> <span class="required">*</span></td>
                            <td class="value">
                                <input class="input-text required-entry" type="text" name="priority[ctp_priority_value]" id="ctp_priority_value" value="<?php echo $this->getPriority()->getctp_priority_value(); ?>"></input>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        
    </form>
<script type="text/javascript">
    priorityForm = new varienForm('priority_form', '');
</script> 

    

</div>

