<?php
    $_helper = $this->helper('catalog/output');
    $_product = $this->getProduct();
?>
<ul class="messages ap-dialog-messages">
	<li class="success-msg ap-dialog-success-message">
		<span><?php echo $this->__('%s was added to your shopping cart.', $this->getProduct()->getName()); ?></span>
	</li>
</ul>
<div class="product-shop">
	<div class="product-img-box" style="float: left; margin: 0px 10px 0px 0px">
		<?php
	        $_img = '<img id="image" src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(60).'" style="width: 60px; height: 60px; border: 0px;" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'"/>';
	       echo $_helper->productAttribute($_product, $_img, 'image');
	    ?>
	</div>
	<div class="product-name">
		<h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
		<?php if($_product->isSaleable()): ?>
		    <p class="availability in-stock"><?php echo $this->__('Availability:') ?> <span><?php echo $this->__('In stock') ?></span></p>
		<?php else: ?>
		    <p class="availability out-of-stock"><?php echo $this->__('Availability:') ?> <span><?php echo $this->__('Out of stock') ?></span></p>
		<?php endif; ?>
	</div>
</div>	
<div style="text-align: center; margin-top: 15px;">
	<button class="button ap-dialog-button" type="button" onclick="ewcart.close();"><span><span><?php echo $this->__('Continue Shopping'); ?></span></span></button>
	&nbsp;
	<button class="button ap-dialog-button" type="button" onclick="location.href='<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK);?>checkout/cart/'; ewcart.close();"><span><span><?php echo $this->__('View Shopping Cart'); ?></span></span></button>
</div>
<script type="text/javascript">    
//<![CDATA[
<?php if ((int)$this->mHelper('config')->getDialogDisplayTime() > 0):?>
ewcart.close(<?php echo (int)$this->mHelper('config')->getDialogDisplayTime(); ?>);
<?php endif; ?>
<?php
	$_javascript = $this->getJavascript();
	foreach ($_javascript as $_js) {
		echo "{$_js}\n";
	}
?>
ewcart.rewritePage();
//]]>
</script>
