<?php echo $this->getChildHtml('myblockname'); ?>

<?php $_order = $this->getOrder() ?>

<?php
$orderAdminDate = $this->formatDate($_order->getCreatedAtDate(), 'medium', true);
$orderStoreDate = $this->formatDate($_order->getCreatedAtStoreDate(), 'medium', true);
?>
<div class="box-left">
	<!--Order Information-->
	<div class="entry-edit">
		<?php if ($_order->getEmailSent()):
			$_email=$this->__('Order confirmation email sent');
		else:
			$_email=$this->__('Order confirmation email not sent');
		endif; ?>
		<div class="entry-edit-head">
		<?php if ($this->getNoUseOrderLink()): ?>
			<h4 class="icon-head head-account"><?php echo Mage::helper('sales')->__('Order # %s', $_order->getRealOrderId()) ?> (<?php echo $_email ?>)</h4>
		<?php else: ?>
			<a href="<?php echo $this->getViewUrl($_order->getId()) ?>"><?php echo Mage::helper('sales')->__('Order # %s', $_order->getRealOrderId()) ?></a>
			<strong>(<?php echo $_email ?>)</strong>
		<?php endif; ?>
		</div>
		<div class="fieldset">
			<table cellspacing="0" class="form-list">
			<tr>
				<td class="label"><label><?php echo Mage::helper('sales')->__('Order Date') ?></label></td>
				<td><strong><?php echo $orderAdminDate ?></strong></td>
			</tr>
			<?php if ($orderAdminDate != $orderStoreDate):?>
			<tr>
				<td class="label"><label><?php echo Mage::helper('sales')->__('Order Date (%s)', $_order->getCreatedAtStoreDate()->getTimezone()) ?></label></td>
				<td><strong><?php echo $orderStoreDate ?></strong></td>
			</tr>
			<?php endif;?>
			<tr>
				<td class="label"><label><?php echo Mage::helper('sales')->__('Order Status') ?></label></td>
				<td><strong><span id="order_status"><?php echo $_order->getStatusLabel() ?></span></strong></td>
			</tr>
			<tr>
				<td class="label"><label><?php echo Mage::helper('sales')->__('Purchased From') ?></label></td>
				<td><strong><?php echo $this->getOrderStoreName() ?></strong></td>
			</tr>
			<?php if($_order->getRelationChildId()): ?>
			<tr>
				<td class="label"><label><?php echo Mage::helper('sales')->__('Link to the new order') ?></label></td>
				<td><a href="<?php echo $this->getViewUrl($_order->getRelationChildId()) ?>">
					<?php echo $_order->getRelationChildRealId() ?>
				</a></td>
			</tr>
			<?php endif; ?>
			<?php if($_order->getRelationParentId()): ?>
			<tr>
				<td class="label"><label><?php echo Mage::helper('sales')->__('Link to the previous order') ?></label></td>
				<td><a href="<?php echo $this->getViewUrl($_order->getRelationParentId()) ?>">
					<?php echo $_order->getRelationParentRealId() ?>
				</a></td>
			</tr>
			<?php endif; ?>
			<?php if($_order->getRemoteIp()): ?>
			<tr>
				<td class="label"><label><?php echo Mage::helper('sales')->__('Placed from IP') ?></label></td>
				<td><strong><?php echo $_order->getRemoteIp() ?></strong></td>
			</tr>
			<?php endif; ?>
			<?php if($_order->getGlobalCurrencyCode() != $_order->getBaseCurrencyCode()): ?>
			<tr>
				<td class="label"><label><?php echo Mage::helper('sales')->__('%s / %s rate:', $_order->getGlobalCurrencyCode(), $_order->getBaseCurrencyCode()) ?></label></td>
				<td><strong><?php echo $_order->getBaseToGlobalRate() ?></strong></td>
			</tr>
			<?php endif; ?>
			<?php if($_order->getBaseCurrencyCode() != $_order->getOrderCurrencyCode()): ?>
			<tr>
				<td class="label"><label><?php echo Mage::helper('sales')->__('%s / %s rate:', $_order->getOrderCurrencyCode(), $_order->getBaseCurrencyCode()) ?></label></td>
				<td><strong><?php echo $_order->getBaseToOrderRate() ?></strong></td>
			</tr>
			<?php endif; ?>
			</table>
		</div>
	</div>
</div>
<div class="box-right">
	<!--Account Information-->
	<div class="entry-edit">
		<div class="entry-edit-head">
			<h4 class="icon-head head-account"><?php echo Mage::helper('sales')->__('Account Information') ?></h4>
		</div>
		<div class="fieldset">
			<div class="hor-scroll">
				<table cellspacing="0" class="form-list">
				<tr>
					<td class="label"><label><?php echo Mage::helper('sales')->__('Customer Name') ?></label></td>
					<td>
					<?php if ($_customerUrl=$this->getCustomerViewUrl()) : ?>
						<a href="<?php echo $_customerUrl ?>" target="_blank"><strong><?php echo $this->htmlEscape($_order->getCustomerName()) ?></strong></a>
					<?php else: ?>
						<strong><?php echo $this->htmlEscape($_order->getCustomerName()) ?></strong>
					<?php endif; ?>
					</td>
				</tr>
				<tr>
					<td class="label"><label><?php echo Mage::helper('sales')->__('Email') ?></label></td>
					<td><a href="mailto:<?php echo $_order->getCustomerEmail() ?>"><strong><?php echo $_order->getCustomerEmail() ?></strong></a></td>
				</tr>
				<?php if ($_groupName=$this->getCustomerGroupName()) : ?>
				<tr>
					<td class="label"><label><?php echo Mage::helper('sales')->__('Customer Group') ?></label></td>
					<td><strong><?php echo $_groupName ?></strong></td>
				</tr>
				<?php endif; ?>
				<?php if ($_dob=$this->getOrder()->getCustomerDob()) : ?>
				<tr>
					<td class="label"><label><?php echo Mage::helper('sales')->__('Date of Birth') ?></label></td>
					<td><strong><?php echo Mage::helper('core')->formatDate($_dob, 'medium') ?></strong></td>
				</tr>
				<?php endif; ?>
				<?php if ($_taxvat = $_order->getCustomerTaxvat()):?>
				<tr>
					<td class="label"><label><?php echo Mage::helper('sales')->__('TAX/VAT Number') ?></label></label></td>
					<td><strong><?php echo $this->htmlEscape($_taxvat)?></strong></td>
				</tr>
				<?php endif;?>
				</table>
			</div>
		</div>
	</div>

	<?php
	if (Mage::getStoreConfig('salesrep/module_status/enabled')) {
 		$admins   = Mage::getModel('LucidPath_SalesRep_Model_Source_UsersList')->toOptionArray();
		$statuses = Mage::helper('salesrep')->getStatusList();
		$salesrep = Mage::getModel('salesrep/salesrep')->loadByOrder($_order);
		$current_admin = Mage::getSingleton('admin/session')->getUser();
	?>
		<div class="entry-edit">
			<div class="entry-edit-head">
				<h4 class="icon-head head-salesrep"><?php echo Mage::helper('sales')->__('Sales Representative') ?></h4>
			</div>
			<fieldset>

				<form id="co-salesrep-form" action="">
					<input type="hidden" name="order_id" value="<?php echo $_order->getId(); ?>" />
					<ul class="form-list">
						<li>
							<div class="input-box">
								<table border="0">
								<tr>
									<?php
									echo '<!-- '. Mage::getStoreConfig('salesrep/setup/users_can_see') .' -->';
									if (Mage::getSingleton('admin/session')->isAllowed('system/config') ||
										Mage::getStoreConfig('salesrep/setup/users_can_see') == 1 ||
										Mage::getStoreConfig('salesrep/setup/users_can_see') == 2 ||
										(Mage::getStoreConfig('salesrep/setup/users_can_see') == 3 && $current_admin->getId() == $salesrep->getAdminId())) {
									?>
										<td>
											Name:
										</td>
										<td width="16"></td>
										<td>
											<?php
											if (Mage::getSingleton('admin/session')->isAllowed('sales/order/actions/salesrep/change_salesrep_name')) {
											?>
												<select style="width: 200px;" id="salesrep_user_id" name="salesrep_user_id" class="validate-select">
													<?php foreach($admins as $admin): ?>
													<option <?php if ($salesrep->getAdminId() == $admin['value']) echo 'selected="selected"';?> value="<?php echo $admin['value'] ?>"><?php echo $admin['label'] ?></option>
													<?php endforeach; ?>
												</select>
											<?php
											} else {
												if ($salesrep->getAdminName() != "") {
													echo $salesrep->getAdminName();
												} else {
													echo $this->__('No Sales Representative');
												}
											}
											?>
										</td>
									<?php
									} else {
									?>
									<td>No information available</td>
									<?php
									}
									?>
								</tr>
								<?php
								if (Mage::getSingleton('admin/session')->isAllowed('system/config') ||
									Mage::getStoreConfig('salesrep/setup/users_can_see') == 2) {
								?>
									<tr>
										<td>
											Commission:
										</td>
										<td width="16"></td>
										<td>
											<span id="salesrep_commission_earned">
												<?php
													if ($salesrep->getCommissionEarned() != "") {
														echo Mage::helper('core')->currency($salesrep->getCommissionEarned(), true, false);
													}
												?>
											</span>
										</td>
									</tr>
								<?php
								} else {
									$admin = Mage::getSingleton('admin/session')->getUser();

									if ($admin->getId() == $salesrep->getAdminId()) {
								?>
									<tr>
										<td>
											Commission:
										</td>
										<td width="16"></td>
										<td>
											<span id="salesrep_commission_earned">
												<?php
													if ($salesrep->getCommissionEarned() != "") {
														echo Mage::helper('core')->currency($salesrep->getCommissionEarned(), true, false);
													}
												?>
											</span>
										</td>
									</tr>
								<?php
									}
								}
								?>
								<?php
								if (Mage::getSingleton('admin/session')->isAllowed('system/config') ||
									Mage::getStoreConfig('salesrep/setup/users_can_see') == 2) {
								?>
									<tr>
										<td>
											Payment Status:
										</td>
										<td width="16">
											<?php
												if ($salesrep->getCommissionStatus() != "") {
													$_salesrep_icon = $this->getSkinUrl('images/salesrep/'. strtolower($salesrep->getCommissionStatus()) .'.png');
												} else {
													$_salesrep_icon = $this->getSkinUrl('images/salesrep/unpaid.png');
												}
											?>
											<img style="margin-top: 2px;" name="salesrep_commission_status_icon" id="salesrep_commission_status_icon" src="<?php echo $_salesrep_icon; ?>" alt="<?php echo $salesrep->getCommissionStatus(); ?>"/>
										</td>
										<td>
										<?php
										if (Mage::getSingleton('admin/session')->isAllowed('sales/order/actions/salesrep/change_salesrep_commission_status')) {
										?>
											<select style="width: 200px;" id="salesrep_commission_status" name="salesrep_commission_status" class="validate-select">
												<?php foreach($statuses as $status): ?>
												<option <?php if ($salesrep->getCommissionStatus() == $status['value']) echo 'selected="selected"';?> value="<?php echo $status['value'] ?>"><?php echo $status['label'] ?></option>
												<?php endforeach; ?>
											</select>
										<?php
										} else {
											if ($salesrep->getCommissionStatus() != "") {
												echo $salesrep->getCommissionStatus();
											} else {
												echo "Unpaid";
											}
										}
										?>
										</td>
									</tr>
								<?php
								} else {
									$admin = Mage::getSingleton('admin/session')->getUser();

									if ($admin->getId() == $salesrep->getAdminId()) {
								?>
									<tr>
										<td>
											Payment Status:
										</td>
										<td width="16"></td>
										<td>
											<span id="salesrep_commission_status">
												<?php
												if ($salesrep->getCommissionStatus() != "") {
													echo $salesrep->getCommissionStatus();
												} else {
													echo "Unpaid";
												}
												?>
											</span>
										</td>
									</tr>
								<?php
									}
								}
								?>
								</table>
							</div>
						</li>
					</ul>
				</form>
			</fieldset>
		</div>
	<?php
	}
	?>
</div>
<div class="clear"></div>

<div class="box-left">
	<!--Billing Address-->
	<div class="entry-edit">
		<div class="entry-edit-head">
			<h4 class="icon-head head-billing-address"><?php echo Mage::helper('sales')->__('Billing Address') ?></h4>
		</div>
		<fieldset>
			<address><?php echo $_order->getBillingAddress()->getFormated(true) ?></address>
		</fieldset>
	</div>
</div>
<?php if (!$this->getOrder()->getIsVirtual()): ?>
<div class="box-right">
	<!--Shipping Address-->
	<div class="entry-edit">
		<div class="entry-edit-head">
			<h4 class="icon-head head-shipping-address"><?php echo Mage::helper('sales')->__('Shipping Address') ?></h4>
		</div>
		<fieldset>
			<address><?php echo $_order->getShippingAddress()->getFormated(true) ?></address>
		</fieldset>
	</div>
</div>
<div class="clear"></div>
<?php endif; ?>


<?php
if (Mage::getStoreConfig('salesrep/module_status/enabled') &&
	Mage::getSingleton('admin/session')->isAllowed('sales/order/actions/salesrep/change_salesrep_name')) {
?>
<script type="text/javascript">
//<![CDATA[
function changeSalesrepName() {
	var request = new Ajax.Request(
		'<?php echo $this->getUrl('adminhtml/order/changeSalesrep/') ?>',
		{
			method: 'post',
			onComplete: function() {},
			onSuccess: function(data) {
				$("salesrep_commission_earned").innerHTML = data.responseText;
			},
			onFailure: function() {},
			parameters: Form.serialize(this.form)
		}
	);
	return false;
}

var salesrep_commission_status = $('salesrep_commission_status').value.toLowerCase();

function changeCommissionStatus() {
	var request = new Ajax.Request(
		'<?php echo $this->getUrl('adminhtml/order/changeCommissionStatus/') ?>',
		{
			method: 'post',
			onComplete: function() {},
			onSuccess: function(data) {
				$("salesrep_commission_status_icon").src = $("salesrep_commission_status_icon").src.replace(salesrep_commission_status, $('salesrep_commission_status').value.toLowerCase());

				salesrep_commission_status = $('salesrep_commission_status').value.toLowerCase();
			},
			onFailure: function() {},
			parameters: Form.serialize(this.form)
		}
	);
	return false;
}

Event.observe($('salesrep_user_id'), 'change', changeSalesrepName);
Event.observe($('salesrep_commission_status'), 'change', changeCommissionStatus);
//]]>
</script>
<?php
}
?>