<div class="entry-edit">
    <div class="content-header">
        <table cellspacing="0" class="grid-header">
            <tr>
                <td><h3><?php echo $this->getTitle(); ?></h3></td>
                <td align="right">
                    <button onclick="setLocation('<?php echo $this->getBackUrl(); ?>');" class="scalable back" type="button"><span><?php echo $this->__('Back') ?></span></button>
                        <button onclick="document.location.href='<?php echo $this->getDeleteUrl() ?>'" class="scalable delete" type="button"><span><?php echo $this->__('Delete') ?></span></button>
                    <button onclick="statusForm.submit();" class="scalable save" type="button"><span><?php echo $this->__('Save'); ?></span></button>
                </td>
            </tr>
        </table>
    </div>

    <form id="status_form" method="POST" name="status_form" action="<?php echo $this->getUrl("*/*/Save"); ?>">
        <div>
            <input type="hidden" id="form_key" name="form_key"  value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
            <input type="hidden" id="cts_id" name="cts_id"  value="<?php echo $this->getStatus()->getId() ?>" />
        </div>
        <div id="ticket_fieldset" class="fieldset ">
            <div class="hor-scroll">
                <table class="form-list" cellspacing="0">
                    <tbody>
                        <tr>
                            <td class="label"><?php echo $this->__('Name'); ?> <span class="required">*</span></td>
                            <td class="value">
                                <input class="input-text required-entry" type="text" name="status[cts_name]" id="cts_name" value="<?php echo $this->getStatus()->getcts_name(); ?>"></input>
                            </td>
                        </tr>
                        <tr>
                            <td class="label"><?php echo $this->__('Order'); ?> <span class="required">*</span></td>
                            <td class="value">
                                <input class="input-text required-entry" type="text" name="status[cts_order]" id="cts_order" value="<?php echo $this->getStatus()->getcts_order(); ?>"></input>
                            </td>
                        </tr>
                        <tr>
                            <td class="label"><?php echo $this->__('Is a system status'); ?></td>
                            <td class="value">
                                <?php echo ($this->getStatus()->getcts_is_system() ? $this->__('Yes') : $this->__('No')); ?>
                            </td>
                        </tr>
                        <tr>
                            <td class="label"><?php echo $this->__('Allow customer change'); ?> <span class="required">*</span></td>
                            <td class="value">
                                <select class=" required-entry select" name="status[cts_customer_can_change]" id="cts_customer_can_change">
                                    <?php foreach ($this->getBoolean() as $k => $v) : ?>
                                        <option <?php if ($this->getStatus()->getcts_customer_can_change() == $v) echo "selected" ?> value="<?php echo $v; ?>"><?php echo $k; ?></option>
                                    <?php endforeach; ?>    
                                </select>
                            </td>
                        </tr>                        
                    </tbody>
                </table>
            </div>
        </div>
        
    </form>
<script type="text/javascript">
    statusForm = new varienForm('status_form', '');
</script> 

    

</div>

