<!--
/**
* Magento
*
* NOTICE OF LICENSE
*
* This source file is subject to the Open Software License (OSL 3.0)
* It is also available through the world-wide-web at this URL:
* http://opensource.org/licenses/osl-3.0.php
*
* @copyright  Copyright (c) 2013 Boost My Shop (http://www.boostmyshop.com)
* @author : Nicolas MUGNIER
* @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
* @package MDN_MarketPlace
* @version 2.1
*/
-->
<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3 class="icon-head head-customer"><?php echo $this->__('Marketplace Configuration'); ?></h3></td>
            <td class="a-right"><?php echo $this->getChildHtml('save_button'); ?>
            </td>
        </tr>
    </table>
</div>
<?php echo $this->getFormHtml(); ?>
