<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Afptc
 * @version    1.1.12
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><script type="text/javascript">
    document.observe('dom:loaded', function() {
        if ($('awafptc_popup_display_on_checkout_or_cart_only')) {
            pel = $('awafptc_popup_display_on_checkout_or_cart_only').parentElement;
            pel.innerHTML = '<?php echo $this->getACPNote(); ?>';
            scope = pel.parentElement.select('.scope-label');
            if (typeof(scope.first()) != 'undefined') {
                scope.first().hide();
            }
            usedef = pel.parentElement.select('.use-default');
            if (typeof(usedef.first()) != 'undefined') {
                usedef.first().hide();
            }
        }
    });
</script>
