<!--@subject Compte créé @-->

<div style="font:11px/1.35em Verdana, Arial, Helvetica, sans-serif;">
    <table cellspacing="0" cellpadding="0" border="0" width="98%" style="margin-top:10px; font:11px/1.35em Verdana, Arial, Helvetica, sans-serif; margin-bottom:10px;">
        <tr>
            <td align="center" valign="top">
                <!-- [ header starts here] -->
                <table cellspacing="0" cellpadding="0" border="0" width="650">
                    <tr>
                        <td valign="top"><a href="{{store url=""}}"><img src="{{skin url="images/logo_email.gif" _area='frontend'}}" alt="{{var store.getFrontendName()}}"  style="margin-bottom:10px;" border="0"/></a></td>
                    </tr>
                </table>
                <!-- [ middle starts here] -->
                <table cellspacing="0" cellpadding="0" border="0" width="650">
                    <tr>
                        <td valign="top">
                            <p>Bonjour {{var customer_name}},</p>
                            <br/>
                            <p>Un compte a &eacute;t&eacute; cr&eacute;&eacute; automatiquement suite &agrave; votre demande de contact :</p>
                            <p>Email : {{var email}}</p>
                            <p>Mot de passe : {{var password}}</p>
                            <br/>
                            <p>Utilisez ce compte pour vos prochains &eacute;change et pour passer commande.</p>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</div>