<div class="entry-edit">
    <div class="content-header">
        <table cellspacing="0" class="grid-header">
            <tr>
                <td>
                  <h3><?php echo $this->__('Email router rules') ?></h3>
                </td>
                <td align="right">
                    <button onclick="setLocation('<?php echo $this->getUrl('*/*/New') ?>')" class="scalable save" type="button"><span><?php echo $this->__('Add a new rule') ?></span></button>
                </td>
            </tr>
        </table>
    </div>
    <?php echo $this->getGridParentHtml(); ?>
</div>