<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright  Copyright (c) 2012 Boost My Shop (http://www.boostmyshop.com)
 * @author : Nicolas MUGNIER
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @package MDN_MarketPlace
 * @version 2.1
 */
?>

<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?php echo $this->__('Category associations') ?></h3></td>
        </tr>
    </table>
</div>

<form id="formData" name="formData" action="<?php echo mage::helper('adminhtml')->getUrl('MarketPlace/Categories/Save'); ?>" method="POST">
    <input id="form_key" name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
    <div class="entry-edit">
        <div class="grid">
            <table class="data" cellspacing="0" width="100%">
                <thead>
                    <tr class="headings">
                        <th class="a-center"><?php echo $this->__('Category') ?></th>
                        <?php foreach ($this->getMarketPlaces() as $marketPlace): ?>
                            <th class="a-center"><?php echo $marketPlace->getMarketPlaceName(); ?></th>
                        <?php endforeach; ?>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->getCategories() as $category): ?>
                        <?php $indent = ''; ?>
                        <?php for ($i = 0; $i <= $category->getDepth(); $i++): ?>
                            <?php $indent .= '|-----'; ?>
                        <?php endfor; ?>
                        <tr>
                            <td><?php echo $indent . $category->getName(); ?></td>
                            <?php foreach ($this->getMarketPlaces() as $marketPlace): ?>
                                <td align="center">
                                    <?php echo $this->getAssociationDescription($category, $marketPlace); ?> 
                                    &nbsp; (<a href="<?php echo mage::helper('adminhtml')->getUrl('MarketPlace/Categories/Edit', array('category_id' => $category->getId(), 'marketplace' => $marketPlace->getMarketPlaceName())); ?>"><?php echo $this->__('Edit'); ?></a>)
                                </td>							
                            <?php endforeach; ?>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>

</form>