<?php if($this->getItemCollection() && count($this->getItemCollection()->getItems())): ?>
<?php $colWidth = round(100/$this->getColumnCount()); ?>
<div style="margin-bottom:15px;">
    <h3 style="margin-bottom:0px;"><?php echo $this->getTitle(); ?></h3>
    <table class="products-grid" border="0" cellpadding="0" cellspacing="10" width="100%">
    <?php $this->resetItemsIterator() ?>
    <?php for($_i=0;$_i<$this->getRowCount();$_i++): ?>
        <tr>
        <?php for($_j=0;$_j<$this->getColumnCount();$_j++): ?>
            <?php if($_link=$this->getIterableItem()): ?>
            <td width="<?php echo $colWidth; ?>%">
                <table  border="0" cellpadding="0" cellspacing="0" width="200px" style="font-weight: bold;font-size: 15px;font-family:Arial, Helvetica, sans-serif;">
                    <tr>
                        <td>
                            <a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>" class="product-image">
                                <img src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image')->resize(125) ?>" width="125" height="125" alt="<?php echo $this->htmlEscape($_link->getName()) ?>" />
                            </a>
                            <h3 class="product-name">
                                <a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>" style="font:15px Arial, Helvetica, sans-serif;color: #444;">
                                    <?php echo $this->htmlEscape($_link->getName()) ?>
                                </a>
                            </h3>
                            <?php echo $this->getPriceHtml($_link, true) ?>
                        </td>
                    </tr>
                </table>

            </td>
            <?php else: ?>
            <td class="empty">&nbsp;</td>
            <?php endif; ?>
        <?php endfor; ?>
        </tr>
    <?php endfor; ?>
    </table>
</div>
<?php endif ?>
