<script type="text/javascript">
//<![CDATA[
<?php $_groups = $this->getGroups(); ?>
// types
var cbpTypes = {};
<?php foreach ($_groups as $_group): ?>
cbpTypes['<?php echo $_group->getId() ?>'] = <?php echo $_group->getCbpType() ?>;
<?php endforeach; ?>
// amounts
var cbpAmounts = {};
<?php foreach ($_groups as $_group): ?>
cbpAmounts['<?php echo $_group->getId() ?>'] = <?php echo $_group->getAmount() ?>;
<?php endforeach; ?>
cbpLabel = '<?php echo Mage::helper('aitcbp')->__('Cost based price') ?>';
cbpTierLabel = '<?php echo Mage::helper('aitcbp')->__('Tier price') ?>';
currencyCode = '[<?php echo $this->_getCurrencyCode() ?>]';
//]]>
</script>

