<?php
/**
 * OneStepCheckout
 * 
 * NOTICE OF LICENSE
 *
 * This source file is subject to One Step Checkout AS software license.
 *
 * License is available through the world-wide-web at this URL:
 * https://www.onestepcheckout.com/LICENSE.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to mail@onestepcheckout.com so we can send you a copy immediately.
 *
 * @category   Idev
 * @package    Idev_OneStepCheckout
 * @copyright  Copyright (c) 2009 OneStepCheckout  (https://www.onestepcheckout.com/)
 * @license    https://www.onestepcheckout.com/LICENSE.txt
 */
?>
var quoteBaseGrandTotal = <?php echo (float)$this->_getQuote()->getBaseGrandTotal(); ?>;
var isGiftCardApplied = <?php if($this->isFullyPaidAfterApplication()): ?>true<?php else: ?>false<?php endif; ?>;
if (quoteBaseGrandTotal < 0.0001 && isGiftCardApplied) {
    Payment.prototype.init = function () {
        var elements = Form.getElements(this.form);
        var method = null;
        for (var i=0; i < elements.length; i++) {
            if (elements[i].name == 'payment[method]' && elements[i].value == 'free') {
                elements[i].checked = true;
                method = 'free';
            } else {
                elements[i].disabled = true;
                (elements[i]).parentNode.hide();
                if(elements[i].name == 'payment[method]'){
                    $methodForm = $('container_payment_method_' + elements[i].value);
                    if($methodForm){
                        $methodForm.hide();
                    }
                }
            }
        }
        if (method) this.switchMethod(method);
    };
}
payment.init();
Payment.prototype.init = function () {};
