<?php /** @var $this Ophirah_Qquoteadv_Block_Qquote */ ?>
<?php if ($this->getQuote()->getData() == array()): ?>

    <div class="page-title">
        <h1><?php echo $this->__('Request for Quote') ?></h1>
    </div>
    <div class="cart-empty">
        <p><?php echo $this->__('No Items to display.'); ?></p>

        <p><?php echo $this->__('Click <a href="%s">here</a> to continue shopping.', $this->getUrl()) ?></p>
    </div>

<?php else: ?>

    <?php $productNames = $this->getNotSalableProductNames($this->getQuote()); ?>

    <div class="page-title">
        <h1><?php echo $this->__('Request for Quote') ?></h1>
        <?php if ($this->displayAssignedTo()): ?>
            <div class="assigned-to">
                <?php if (Mage::helper('qquoteadv')->getAdminUser() !== null): ?>
                    <?php if ($this->isAssignPreviousEnabled()): ?>
                        <?php if ($this->helper('customer')->isLoggedIn()): ?>
                            <?php
                            $customerData = Mage::getSingleton('customer/session')->getCustomer();
                            echo $this->__('Quote will be assigned to <strong>%s</strong>', Mage::helper('qquoteadv')->getAdminUser(Mage::helper('qquoteadv')->getPreviousAssignedAdmin(null, $customerData->getId()))->getName()); ?>
                        <?php else: ?>
                            <?php echo $this->__('If the end user has no previous assigned sales representative the quote will be assigned to <strong>%s</strong>.', $this->getAdminUser()->getName()); ?>
                        <?php endif; ?>
                    <?php else: ?>
                        <?php echo $this->__('Quote will be assigned to <strong>%s</strong>', $this->getAdminUser()->getName()); ?>
                    <?php endif; ?>
                <?php endif; ?>
            </div>
        <?php endif; ?>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

    <form method='post' id="quotelist" name="quotelist"
          action='<?php echo $this->getUrl('qquoteadv/index/quoteRequest', array('_secure' => true)) ?>'>
    <?php if ($this->displayAssignedTo() && $this->getAdminUser() !== null): ?>
        <input type="hidden" name="user_id" value="<?php echo $this->getAdminUser()->getId(); ?>"/>
    <?php endif; ?>
    <table cellspacing="0" border="0" id="shopping-cart-table" class="data-table cart-table">
    <col width="30"/>
    <col width="75"/>
    <col/>
    <col width="10"/>
    <col width="250"/>
    <col width="60"/>
    <col width="60"/>
    <thead>
    <tr>

        <th><?php echo $this->__('Product') ?></th>
        <th></th>
        <th><?php echo $this->__('Remarks') ?></th>
        <th class="a-center"><?php echo $this->__('Price') ?></th>
        <th class="a-center"><?php echo $this->__('Qty') ?> <span class="required"></span></th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    <?php
    $i = 0;
    foreach ($this->getQuote() as $item):

        $product = $this->getProduct($item->getProductId());

        if ($product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_CONFIGURABLE) {
            $childProduct = Mage::getModel('qquoteadv/qqadvproduct')->getConfChildProduct($item->getId());
        } else {
            $childProduct = $product;
        }
        ?>
        <tr>

            <?php
            $attributes = unserialize($item->getAttribute());
            $original_product = Mage::getModel('catalog/product')->load($attributes['product']);
            $original_product_url = $original_product->getProductUrl();
            ?>
            <td><a class="product-image" href="<?php echo $original_product_url; ?>"><img
                        src=" <?php echo Mage::helper('catalog/image')->init($product, 'thumbnail')->resize(180); ?>"
                        alt="<?php echo $item->getName(); ?>"/></a>

                <div class="a-center">
                    <a href="<?php echo $this->getUrl('qquoteadv/index/configure', array('id' => $item->getId())) ?>"><?php echo $this->__("Edit") ?></a>
                </div>
            </td>
            <td class="attributes-col"><h2 class="title product-name">
                    <?php if (1): //$product->hasProductUrl()):?>
                        <a href="<?php echo $product->getProductUrl() ?>"><?php echo $this->htmlEscape($product->getName()) ?></a>
                    <?php else: ?>
                        <?php echo $this->htmlEscape($item->getName()) ?>
                    <?php endif; ?>
                </h2>

                <div class="product-cart-sku">
                    <span class="label"><?php echo $this->__('Sku: '); ?></span><?php echo $product->getSku(); ?>
                </div>
                <?php
                if ($product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_BUNDLE || $product->isConfigurable() || $product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_SIMPLE):
                    $quoteByProduct = Mage::helper('qquoteadv')->getQuoteItem($product, $item->getAttribute(), null, $item);

                    foreach ($quoteByProduct->getAllItems() as $_item) {
                        if ($_item->getProductId() == $product->getId()) {
                            echo $this->getItemHtml($_item);
                        }
                    }

                    $qty = $quoteByProduct->getItemsQty();

                    // Select price with or without tax
                    if (Mage::getStoreConfig('tax/calculation/price_includes_tax') == 1):
                        $_finalPrice = $quoteByProduct->getGrandTotal() / ($qty > 0 ? $qty : 1);
                    else:
                        $_finalPrice = $quoteByProduct->getSubtotal() / ($qty > 0 ? $qty : 1);
                    endif;

                    /*else:
                        $quoteByProduct = Mage::helper('qquoteadv')->getQuoteItem($product, $item->getAttribute());
                        $qty = $quoteByProduct->getItemsQty();
                        $_finalPrice = $quoteByProduct->getSubtotal() / ($qty>0?$qty:1);
                    ?>
                        <?php if($product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_SIMPLE) : ?>
                        <?php    $_options =  $this->getOptionList($product, $item->getAttribute()); ?>

                        <dl class="item-options">
                            <?php if(is_array($_options)): ?>
                                <?php foreach ($_options as $label=>$_option) : ?>
                                <?php if(empty($label)) continue; ?>
                                <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
                                <dt><?php echo $this->htmlEscape($label) ?></dt>
                                <dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="truncated"<?php endif; ?>><?php echo $_formatedOptionValue['value'] ?>
                                    <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                    <div class="truncated_full_value">
                                        <dl class="item-options">
                                            <dt><?php echo $this->htmlEscape($label) ?></dt>
                                            <dd><?php echo $_formatedOptionValue['full_view'] ?></dd>
                                        </dl>
                                    </div>
                                    <?php endif; ?>
                                </dd>
                                <?php endforeach; ?>
                            <?php endif; ?>
                         </dl>
                        <?php endif; ?>

                    <?php */
                endif; ?>
            </td>
            <td class="quickQuote">
                <?php if ($i > 0): ?>
                    <textarea name="quote_request[<?php echo $item->getId() ?>][client_request]"
                              rows="4">&nbsp;</textarea>
                <?php else: ?>
                    <div id="parent">
                        <textarea id="textArea"
                                  name="quote_request[<?php echo $item->getId() ?>][client_request]"
                                  rows="10"
                                  onclick="$(event.target).value = ''; $(event.target).setAttribute('onclick', '');"
                            ><?php echo $this->__('Be advised to enter your comments') ?></textarea>
                    </div>
                <?php endif; ?>
            </td>
            <td>
                <?php if (Mage::helper('qquoteadv/not2order')->getShowPrice($product)): ?>
                    <?php echo Mage::helper('checkout')->formatPrice($_finalPrice) ?>
                <?php endif; ?>
            </td>
            <td nowrap="nowrap" class="quickQuote">
                <div id="qdiv_<?php echo $item->getId() ?>" nowrap="nowrap" class="qty-div">
                    <input type="text"
                           class="required-entry validate-zero-or-greater required-entry input-text loading"
                           size="6"
                           name="quote_request[<?php echo $item->getId() ?>][qty][]"
                           value="<?php echo $item->getQty(); ?>"/>
                </div>

                <div>
                    <?php if ($this->getShowTrierOption()) : ?>
                        <a href="#" id="add-tier"
                           onClick="addNewLine(<?php echo $item->getId() ?>, 'quote_request[<?php echo $item->getId() ?>][qty][]'); return false;"><?php echo $this->__('Add Qty') ?></a>
                    <?php endif; ?>
                </div>
                <input type="hidden" name="quote[<?php echo $item->getId() ?>][qty]"
                       value="<?php echo $item->getQty(); ?>" size="3"/>&nbsp;
                <input type="hidden" name="quote[<?php echo $item->getId() ?>][attributeEncode]"
                       value="<?php echo base64_encode($item->getAttribute()) ?>"/>
                <input type="hidden" name="quote[<?php echo $item->getId() ?>][product]"
                       value="<?php echo $product->getId() ?>"/>
                <input type="hidden" name="quote[<?php echo $item->getId() ?>][quoteid]"
                       value="<?php echo $item->getId() ?>"/>
            </td>

            <td class="a-center">

                <input type="hidden" id="quote_id" name="quote_id" value="<?php echo $item->getQuoteId() ?>">
                <input type="hidden" class="input-text" name="quote[<?php echo $item->getId() ?>][product]"
                       value="<?php echo $item->getProductId(); ?>" size="3"/>
                <input type="hidden" class="input-text"
                       name="quote_request[<?php echo $item->getId() ?>][product_id]"
                       value="<?php echo $item->getProductId(); ?>" size="6"/>
                <a class="btn-remove btn-remove2" title="<?php echo $this->__('Remove item') ?>"
                   href="<?php echo $this->getUrl('qquoteadv/index/delete', array('id' => $item->getId())); ?>"> <?php echo $this->__('Remove item') ?>
                    "/></a>

            </td>
        </tr>
        <?php
        $i++;
    endforeach;
    ?>
    </tbody>
    <tfoot>
    <tr>
        <td colspan="100" class="a-right">
            <?php if ($this->getContinueShoppingUrl()): ?>
                <button class="button2 btn-continue"
                        onclick="setLocation('<?php echo $this->getContinueShoppingUrl() ?>')" type="button">
                    <span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
            <?php endif; ?>

            <?php $action = "setLocation('" . $this->getUrl('qquoteadv/index/switch2Order') . "');";

            if (count($productNames) > 0) {
                $action = 'initMsg();';
            }
            ?>

            <?php if ($this->getShowOrderReferences()) : ?>
                <button type="button" onclick="<?php echo $action; ?>"
                        title="<?php echo $this->__('Move to Shopping cart') ?>"
                        class="button2 btn-update">
                    <span><span><?php echo $this->__('Move to Shopping cart') ?></span></span></button>
            <?php endif; ?>

            <?php $action = "setLocation('" . $this->getUrl('qquoteadv/index/clearQuote') . "');"; ?>
            <!--<button type="button" onclick="<?php echo $action; ?>" title="<?php echo $this->__('Clear Quote') ?>"
                    class="button" ><span><span><?php echo $this->__('Clear Quote') ?></span></span></button>-->
        </td>
    </tr>
    </tfoot>

    </table>
    <?php if (Mage::getStoreConfig('qquoteadv/quote_form/newsletter_subscribe')): ?>
        <div class="quote-forms">
            <div>
                <input id="chkNews" type="checkbox"
                       name="newsletter"> <?php echo $this->__('Sign up for our newsletter'); ?>
            </div>
        </div>
    <?php endif; ?>
    <div class="quote-forms">
        <?php echo $this->getChildHtml('qquote.address'); ?>
    </div>
    <div id="submit-quote-request">
        <input type='hidden' id='customer_isQuote' name='customer[is_quote]' value='1'/>
        <input style="display:none;" type='submit' name='submitOrder' id="submitOrder" class='form-button'
               value="<?php echo $this->__('Request quote') ?>"/>

        <button onclick="$('submitOrder').click(); event.preventDefault();  event.stopPropagation();"
                class="button btn-proceed-checkout btn-checkout"
                title="<?php echo $this->__('Request quote') ?>" type="button">
            <span><span><?php echo $this->__('Request quote') ?></span></span>
        </button>
    </div>

    <script type="text/javascript">decorateTable('shopping-cart-table')</script>
    </form>

    <script type="text/javascript">
        //<![CDATA[
        var quotelistForm = new VarienForm('quotelist');
        new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>);
        $('country').addClassName('w224');
        new RegionUpdater('shipping_country', 'shipping_region', 'shipping_region_id', <?php echo $this->helper('directory')->getRegionJson() ?>);
        $('shipping_country').addClassName('w224');

        function requestShippingProposal() {
            var elmEmail = $('customer:email');
            if (elmEmail.value) {
                // Send quotelist form to another action
                var quoteShipForm = document.getElementById('quotelist');
                // Reset isQuote to 2
                var isQuote = document.getElementById('customer_isQuote');
                isQuote.value = '2';
                quoteShipForm.action = '<?php echo $this->getUrl('qquoteadv/index/quoteShippingEstimate'); ?>';
                quoteShipForm.submit();

            }
        }

        //]]>
    </script>


<?php
//#show pop-up window
    if (count($productNames) > 0) {
        echo $this->getLayout()->createBlock("core/template")->setTemplate('qquoteadv/quote_lightbox.phtml')->setProductNames($productNames)->toHtml();
    }
    ?>


    <script language="javascript">

        var pool = new Array();

        function addNewLine(itemId, inputName) {
            if (!pool[itemId]) {
                pool[itemId] = 1;
            }

            index = pool[itemId];
            index++;
            pool[itemId] = index;

            var parentElemt = document.getElementById('qdiv_' + itemId);
            var childElem = document.createElement('div');
            childElem.setAttribute("id", 'div_' + itemId + '_' + index);
            parentDiv = 'div_' + itemId + '_' + index;
            inputField = 'quote_' + itemId + '_' + index;
            link = '&nbsp;&nbsp;<a href="#"  onClick="removeElement(\'' + parentDiv + '\', \'' + inputField + '\'); $(\'' + parentDiv + '\').hide()"><img src="<?php echo $this->getSkinUrl('images/minus-icon.png')?>"></a>';

            childElem.innerHTML = '<input size="6" type="text" name="' + inputName + '"  id="quote_' + itemId + '_' + index + '" value=""  class="required-entry validate-zero-or-greater required-entry input-text m5">' + link;

            parentElemt.appendChild(childElem);
        }

        function removeElement(parentElemt, childElemt) {
            var parentDiv = document.getElementById(parentElemt);
            var childElemt = document.getElementById(childElemt);
            parentDiv.removeChild(childElemt);
        }
    </script>
<?php endif; ?>
