<?php
$admins = Mage::helper('salesrep')->getAdminsList();
?>
<form id="co-salesrep-form" action="">
	<ul class="form-list">
		<li>
			<label for="salesrep_name" class="required"><em>*</em><?php echo Mage::getStoreConfig('salesrep/step_setup/step_label')?></label>
			<div class="input-box">	   
				<select id="salesrep_name" name="salesrep_name" class="validate-select">
					<option value=""></option>
					<?php foreach($admins as $admin): ?>
					<option value="<?php echo $admin['value'] ?>"><?php echo $admin['label'] ?></option>
					<?php endforeach; ?>
				</select>
			</div>
			<div style="display: none;" id="advice-validate-select-salesrep-name" class="validation-advice">
				<?php echo Mage::getStoreConfig('salesrep/step_setup/step_error_msg')?>
			</div>
		</li>
	</ul>
</form>

<div class="buttons-set" id="salesrep-buttons-container">
	<p class="required"><?php echo $this->__('* Required Fields') ?></p>
	<p class="back-link"><a href="#" onclick="checkout.back(); return false;"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
	<button type="button" class="button" onclick="salesrep.save()"><span><?php echo $this->__('Continue') ?></span></button>
	<span class="please-wait" id="salesrep-please-wait" style="display:none;">
		<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
	</span>
</div>

<script type="text/javascript">
//<![CDATA[
var Salesrep = Class.create();
Salesrep.prototype = {
	initialize: function(form, saveUrl){
		this.form = form;
		if ($(this.form)) {
			$(this.form).observe('submit', function(event){this.save();Event.stop(event);}.bind(this));
		}
		this.saveUrl = saveUrl;
		this.onSave = this.nextStep.bindAsEventListener(this);
		this.onComplete = this.resetLoadWaiting.bindAsEventListener(this);
	},

	save: function(){
		if (checkout.loadWaiting!=false) return;

		var validator = new Validation(this.form);
		if (validator.validate()) {

			checkout.setLoadWaiting('salesrep');

			var request = new Ajax.Request(
				this.saveUrl,
				{
					method: 'post',
					onComplete: this.onComplete,
					onSuccess: this.onSave,
					onFailure: checkout.ajaxFailure.bind(checkout),
					parameters: Form.serialize(this.form)
				}
			);
		}
	},

	resetLoadWaiting: function(transport){
		checkout.setLoadWaiting(false);
	},

	nextStep: function(transport){
		if (transport && transport.responseText){
			try{
				response = eval('(' + transport.responseText + ')');
			}
			catch (e) {
				response = {};
			}
		}

		if (response.error){
			if ((typeof response.message) == 'string') {
				alert(response.message);
			} else {
				if (window.billingRegionUpdater) {
					billingRegionUpdater.update();
				}

				alert(response.message.join("\n"));
			}

			return false;
		}

		checkout.setStepResponse(response);
	}	 
}

var salesrep = new Salesrep('co-salesrep-form', '<?php echo $this->getUrl('checkout/onepage/saveSalesrep') ?>');
//]]>
</script>