<?php
$_helper          =  Mage::helper('catalogsearch');
$_value           = $_helper->getEscapedQueryText();
$_currentCategory = Mage::getSingleton('core/app')->getRequest()->getParam('cat');
$_currentIndex    = Mage::getSingleton('core/app')->getRequest()->getParam('index');
$_filterType      = $this->getFilterType();
$_url             = $this->getAjaxUrl();
?>

<form id="search_mini_form" action="<?php echo $_helper->getResultUrl() ?>" method="get"
    class="searchautocomplete UI-SEARCHAUTOCOMPLETE"
    data-tip="<?php echo $this->__(Mage::getStoreConfig('searchautocomplete/general/tip')) ?>"
    data-url="<?php echo $_url ?>"
    data-minchars="<?php echo Mage::getStoreConfig('searchautocomplete/general/min_chars') ?>"
    data-delay="<?php echo Mage::getStoreConfig('searchautocomplete/general/delay') ?>">

    <div class="form-search">
        <?php if ($_filterType == 'index'): ?>
            <div class="nav-search-in">
                <span class="category-fake UI-CATEGORY-TEXT"><?php echo $this->__('All') ?></span>
                <span class="nav-down-arrow"></span>
                <select name="index" class="category UI-CATEGORY">
                    <option value="0"><?php echo $this->__('All') ?></option>
                    <?php foreach ($this->getIndexes() as $_code => $_name): ?>
                    <option value="<?php echo $_code ?>" <?php if ($_currentIndex == $_code): ?>selected<?php endif ?>>
                        <?php echo $_name ?>
                    </option>
                    <?php endforeach ?>
                </select>
            </div>
        <?php endif ?>

        <input id="search" type="text" name="<?php echo $_helper->getQueryParamName() ?>" placeholder="Enter your search here" value="" class="input-text UI-SEARCH UI-NAV-INPUT search" maxlength="<?php echo $_helper->getMaxQueryLength();?>" />
        
        <button type="submit" title="<?php echo $this->__('Search') ?>" class="submit"><span class="fa fa-search fa-flip-horizontal"></span></button>
        
          <div class="searchautocomplete-loader UI-LOADER" style="display:none;"></div>
        <div style="display: none;" id="search_autocomplete" class="UI-PLACEHOLDER search-autocomplete">
			<div class="top"></div>
		</div>  
    </div>
</form>



<script>
	var baseurl="<?php echo $this->getUrl('catalogsearch/advanced/result/'); ?>";
	$j(document).ready(function (){
		$j( "#search" ).autocomplete({
        source: '/featured-products/searchcustom/index'
        /*select: function( event , ui ) {
			var suitable='';
			suitable=ui.item.label;
			window.location.href = baseurl+'?suitable='+suitable;
            
        }*/

    });
    
});
	
	
	
</script>

