<?php
    $_helper = $this->helper('catalog/output');
    $_product = $this->getProduct();
?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="ewcart-product ewcart-product-grouped">
<form action="<?php echo $this->getAddToCartUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
	<div class="no-display">
		<input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
		<input type="hidden" name="related_product" id="related-products-field" value="" />
		<input type="hidden" name="__ready" value="1" />
	</div>
	
	<div class="product-shop">
		<div class="product-img-box">
			<?php
		        $_img = '<img id="image" src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(60).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
		       echo $_helper->productAttribute($_product, $_img, 'image');
		    ?>
		</div>
		<div class="product-name">
			<h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
		</div>
		
		<?php echo $this->getChildHtml('product_type_data') ?>
		<?php echo $this->getTierPriceHtml() ?>
		<?php echo $this->getChildHtml('other');?>
	
		<?php if ($_product->isSaleable() && $this->hasOptions()):?>
			<?php echo $this->getChildChildHtml('container1', '', true, true) ?>
			<?php echo $this->getChildChildHtml('container2', '', true, true) ?>
		<?php endif;?>
	</div>
	<div class="add-to-box" style="float: right">
		<div class="add-to-cart">
			<button type="button" title="<?php echo $this->__('Add to Cart'); ?>" class="button btn-cart" onclick="productAddToCartForm.submit()"><span><span><?php echo $this->__('Add to Cart'); ?></span></span></button>
		</div>
	</div>
	<div class="clearer"></div>
</form>
</div>
<script type="text/javascript">
//<![CDATA[
	var productAddToCartForm = new VarienForm('product_addtocart_form');
	productAddToCartForm.submit = function(){
			if (this.validator.validate()) {
					this.form.submit();
			}
	}.bind(productAddToCartForm);

	ewcart.rewriteForm();
	EWModalbox.resizeModal();
//]]>
</script>