<?php
            $helper = Mage::helper('cms');
            $processor = $helper->getPageTemplateProcessor();
            // print_r($processor);
?>
<div class="searchindex-result">
    <hr style="color:#E5E5E5">
    <!-- <?php echo $this->getPager() ?> -->
    <ul>
        <?php foreach($this->getCollection() as $_page) : ?> 
        <?php /*echo $processor->filter($_page->getData('content'))*//*echo $processor->filter($_page->getContent());*///print_r(get_class_methods($_page)) ?>
        <li>
            <div class="title">
                <a href="<?php echo Mage::helper('cms/page')->getPageUrl($_page->getData('identifier')) ?>"><?php echo $_page->getData('title') ?></a>
            </div>
            <div class="content">
                <?php 
                    $_html = Mage::helper('cms')->getPageTemplateProcessor()->filter($_page->getContent());
                    $_html = preg_replace('/<script\b[^>]*>(.*?)<\/script>/is', '', $_html);
                ?>
                <?php echo Mage::helper('core/string')->truncate(strip_tags($_html), 300) ?>
            </div>
        </li>
        <?php endforeach ?>
    </ul>
    <hr style="color:#E5E5E5"><!-- <?php echo $this->getPager() ?> -->
</div>
