<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2018 Amasty (https://www.amasty.com)
 * @package Magpleasure_Ajaxreviews
 */
?>
<?php $products = $this->getProducts(); ?>
<?php $helper = Mage::helper('ajaxreviews'); ?>
<!-- Paragraph -->
<table class="row paragraph first">
    <tr>
        <td class="center" align="center">
            <center>
                <table class="container">
                    <tr>
                        <td class="wrapper last">
                            <table class="twelve columns">
                                <tr>
                                    <td>
                                        <p>
                                            <?php
                                            if (count($products) == 1) {
                                                $text = '<a href="' . $products[0]['name'] . '">' . $products[0]['name'] . '</a>';
                                            } else {
                                                $text = '<span>' . $helper->__('goods')   . '</span>';
                                            }
                                            ?>
                                            <span><?php echo $helper->__('Hello %s, you\'ve recently bought' , $this->getCustomerName())?></span>
                                            <span><?php echo $helper->__('%s, what do you think about it?' , $text)?></span>
                                        </p>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                </table>
            </center>
        </td>
    </tr>
</table>
<!-- Paragraph End -->
<?php foreach ($products as $product): ?>
<!-- Product -->
<table class="row product">
    <tr>
        <td class="center" align="center">
            <table class="twelve columns container">
                <tr>
                    <?php if ($product['thumbnail']) : ?>
                    <td class="wrapper">
                        <table class="four columns">
                            <tr>
                                <td class="">

                                    <table class="four columns">
                                        <tr>
                                            <td class="text-pad-left text-pad-right">
                                                <a href="<?php echo $product['url'];?>"
                                                       title="<?php echo $product['name'];?>"
                                                       target="_blank">

                                                    <img alt="<?php echo $product['name'];?>"
                                                             class="thumbnail"
                                                             src="<?php echo $product['thumbnail'];?>"
                                                             width="150"
                                                             height="150">
                                                </a>
                                            </td>
                                            <td class="expander"></td>
                                        </tr>
                                    </table>
                                </td>
                                <td class="expander"></td>
                            </tr>
                        </table>

                    </td>
                    <td class="wrapper last">

                        <table class="eight columns">
                            <tr>
                                <td class="text-pad-left text-pad-right">

                                    <h3><?php echo $product['name'];?></h3>
                                    <span class="purchased"><?php echo $helper->__('Purchased on')?> <?php echo $product['purchase_date'];?>&nbsp;</span>
                                    <br/><br/>

                                    <!--[if mso]>
                                    <v:roundrect xmlns:v="urn:schemas-microsoft-com:vml"
                                                 xmlns:w="urn:schemas-microsoft-com:office:word"
                                                 href="<?php echo $product['review_url'];?>"
                                                 style="height:40px;v-text-anchor:middle;width:300px;"
                                                 arcsize="5%" stroke="f"
                                                 fillcolor="<?php echo $this->getColor();?>">
                                        <w:anchorlock/>
                                        <center style="color:#ffffff;font-family:Helvetica;font-size:16px;font-weight:bold;">
                                            <?php echo $helper->__('Review This Item')?>
                                        </center>
                                    </v:roundrect>
                                    <![endif]-->
                                    <!--[if !mso]-->
                                    <table class="button medium-button radius">
                                        <tr>
                                            <td>
                                                <a href="<?php echo $product['review_url'];?>">
                                                    <?php echo $helper->__('Review This Item')?>
                                                </a>
                                            </td>
                                        </tr>
                                    </table>
                                    <!--[endif]-->

                                </td>
                                <td class="expander"></td>
                            </tr>
                        </table>

                    </td>

                    <?php else: ?>
                    <td class="wrapper">

                        <table class="six columns">
                            <tr>
                                <td class="text-pad-left text-pad-right">

                                    <h3><?php echo $product['name'];?></h3>
                                    <span class="purchased"><?php echo $helper->__('Purchased on')?> <?php echo $product['purchase_date'];?>&nbsp;</span>
                                    <br/><br/>

                                </td>
                                <td class="expander"></td>
                            </tr>
                        </table>

                    </td>

                    <td class="wrapper last">

                        <table class="six columns">
                            <tr>
                                <td class="text-pad-left text-pad-right">

                                    <!--[if mso]>
                                    <v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" 
                                                 xmlns:w="urn:schemas-microsoft-com:office:word"
                                                 href="<?php echo $product['review_url'];?>"
                                                 style="height:40px;v-text-anchor:middle;width:300px;"
                                                 arcsize="5%" stroke="f"
                                                 fillcolor="<?php echo $this->getColor();?>">
                                        <w:anchorlock/>
                                        <center style="color:#ffffff;font-family:Helvetica;font-size:16px;font-weight:bold;">
                                            <?php echo $helper->__('Review This Item')?>
                                        </center>
                                    </v:roundrect>
                                    <![endif]-->
                                    <!--[if !mso]-->
                                    <table class="button medium-button radius">
                                        <tr>
                                            <td>
                                                <a href="<?php echo $product['review_url'];?>">
                                                    <?php echo $helper->__('Review This Item')?>
                                                </a>
                                            </td>
                                        </tr>
                                    </table>
                                    <!--[endif]-->

                                </td>
                                <td class="expander"></td>
                            </tr>
                        </table>
                    </td>
                    <?php endif; ?>
                    <td class="expander"></td>
                </tr>
            </table>
        </td>
    </tr>
</table>
<!-- Product End -->
<?php endforeach; ?>
