<?php
    //define customer id
    $customerId = $this->getRequest()->getParam('id');
    if (!$customerId)
    {
        $order = Mage::registry('current_order');
        if ($order)
        {
            $customerId = $order->getcustomer_id();
        }
    }
?>

<?php /*if ($customerId):*/ ?>
    <?php /*$url = $this->getUrl('CrmTicket/Admin_Ticket/Edit/', array('customer_id' => $customerId));*/ ?>
    <!--<div style="margin-bottom: 15px; margin-top: 10px;">
        <button type="button" class="button" name="button_question" id="button_question" class="scalable " style="" onclick="setLocation('<?php /*echo $url;*/ ?>');" ><span>Add Ticket</span></button>
    </div>-->
<?php /*endif;*/ ?>
<?php echo $this->getGridParentHtml(); ?>
