<table width="100%" border="0" cellpadding="0" cellspacing="0">
    <tr>
        <td>
            <table width="100%" border="0" cellpadding="20" cellspacing="0" style="font-size:20px;color:#444;font-family:verdana;">
                <tr>
                    <td>
                        [datatable:Magento/Categories.Name]
                    </td>
                </tr>
            </table>
        </td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td width="30%">[datatablesnippet(lookup="Category Id" = %datatable:Magento/Categories.Category Id%,offset=0,limit=1):Magento/Products/CategoryLayout]</td>
        <td width="30%">[datatablesnippet(lookup="Category Id" = %datatable:Magento/Categories.Category Id%,offset=1,limit=1):Magento/Products/CategoryLayout]</td>
        <td width="30%">[datatablesnippet(lookup="Category Id" = %datatable:Magento/Categories.Category Id%,offset=2,limit=1):Magento/Products/CategoryLayout]</td>
    </tr>
</table>