<table border="0" cellspacing="5" cellpadding="0" align="center" width="190" style="color:#333;font-family:verdana, Arial;font-size:14px;font-weight:bold;">
    <tr>
        <td>
            <table border="0" cellspacing="0" cellpadding="0" align="center" width="125">
                <tr>
                    <td>
                        <a href="[datatable:Magento/Products.URL]">
                            <img src="[datatable:Magento/Products.Image URL]" width="125">
                        </a>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td>
            <a href="[datatable:Magento/Products.URL]" style="text-decoration:underline;color:#333;font-size:13px;">
            	[datatable:Magento/Products.Name]
            </a>
        </td>
    </tr>
    <tr>
        <td>
            [datatable:Magento/Products.Price Formatted]
        </td>
    </tr>
</table>