<?php
$fefoObj=Mage::getBlockSingleton('Flint_Feefo_Block_Reviews_Widget');
$reviewData=$fefoObj->getReviewsData();
$totalReviews=$reviewData->SUMMARY->TOTALRESPONSES;
$averagereReating=$reviewData->SUMMARY->FIVESTARAVERAGE;
?>
<div itemscope itemtype="http://schema.org/Organization"> 
<meta itemprop="name" content="Choice Stationery Supplies Limited"> 
<meta itemprop="url" content="https://www.choicestationery.com/">
<meta itemprop="telephone" content="01823 250060" />
<div itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
<meta itemprop="streetAddress" content="Lea house" />
<meta itemprop="addressLocality" content="Frobisher Way" />
<meta itemprop="addressLocality" content="Taunton Somerset TA2 6BB" /> 
<meta itemprop="addressCountry" content="UK" />
</div>
<div itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating">
<meta itemprop="ratingValue" content="<?php echo $averagereReating; ?>" />
<meta itemprop="bestRating" content="5"/>
<meta itemprop="worstRating" content="0"/>
<meta itemprop="ratingCount" content="<?php echo $totalReviews; ?>"/>
</div>
</div>