<?php $_product = $this->getProduct() ?>

<?php if (Mage::getStoreConfig('weltpixel_googlecards/general/enable')): ?>
    <?php
    $review = $this->getReviewSummary();
    $reviewCount = $review->getReviewsCount();
    if (!$reviewCount) {
        $reviewCount = 0;
    }
    $ratingSummary = ($review->getRatingSummary()) ? $review->getRatingSummary() : 20;
    ?>
<script type="application/ld+json">
    {
      "@context": "http://schema.org/",
      "@type": "Product",
      "name": "<?php echo htmlentities(strip_tags($_product->getName())) ?>",
      "image": "<?php echo $this->getNonCachedImage($_product) ?>",
      "description": "<?php echo htmlentities(strip_tags($this->getProductDescription($_product))) ?>",
      "sku": "<?php echo htmlentities(strip_tags($_product->getSku())) ?>",
<?php if (strlen(trim($this->getBrand()))): ?>
      "brand": {
        "@type": "Thing",
        "name": "<?php echo $this->getBrand(); ?>"
      },
<?php endif ?>
      "aggregateRating": {
        "@type": "AggregateRating",
        "bestRating": 5,
        "worstRating": 1,
        "ratingValue": "<?php echo $ratingSummary / 20 ; ?>",
        "reviewCount": "<?php echo "13";//$reviewCount ?>"
      },
      "offers": {
        "@type": "Offer",
        "priceCurrency": "<?php echo $this->getCurrencyCode() ?>",
<?php if ($_product->isAvailable()): ?>
        "availability": "http://schema.org/InStock",
 <?php else : ?>
        "availability": "http://schema.org/OutOfStock",
<?php endif; ?>
       "price": "<?php echo $this->getProductPrice() ?>"
      }
    }
</script>
<?php endif ?>