<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright  Copyright (c) 2012 Boost My Shop (http://www.boostmyshop.com)
 * @author : Nicolas MUGNIER
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @package MDN_MarketPlace
 * @version 2.1
 */
?>
<?php $_totals = $this->getTotals(); ?>

<div class="grid">
    <table class="data" cellspacing="0" width="100%" >
        <thead>
            <tr class="headings">
                <th class="a-center"></th>
                <th class="a-center"><?php echo $this->__('Revenue') ?></th>
                <th class="a-center"><?php echo $this->__('Tax') ?></th>
                <th class="a-center"><?php echo $this->__('Shipping') ?></th>
                <th class="a-center"><?php echo $this->__('Quantity') ?></th>
                <!--<th class="a-center">Items</th>-->
            </tr>
        </thead>
        <tbody>
            <?php $i = 0 ?>
            <?php foreach ($_totals as $k => $v): ?>
            <?php $class = ($i % 2 == 0) ? 'event pointer' : 'pointer'; ?>
                <tr class="<?php echo $class; ?>">
                    <td class="a-center"><?php echo $k ?></td>
                    <td class="a-center"><?php echo number_format($v['subtotal'], 2, '.', ',') ?></td>
                    <td class="a-center"><?php echo number_format($v['tax'], 2, '.', ',') ?></td>
                    <td class="a-center"><?php echo number_format($v['shipping'], 2, '.', ',') ?></td>
                    <td class="a-center"><?php echo $v['quantity'] ?></td>
                    <!--<td class="a-center"><?php //echo $v['items'] ?></td>-->
                </tr>
            <?php $i++ ?>
            <?php endforeach ?>
        </tbody>
    </table>
</div>