<?php
/**
 * Extended registration form
 * 
 * @author     Design:Slider GbR <magento@design-slider.de>
 * @copyright  (C)Design:Slider GbR <www.design-slider.de>
 * @license    OSL <http://opensource.org/licenses/osl-3.0.php>
 * @link       http://www.design-slider.de/magento_onlineshop/magento-extensions/registration-address/
 * @package    DS_RegAddress
 * @version    CE 1.7
 */

$requiredClass = $this->getAddressForced() ? 'required' : '';
$requiredCharacter = $this->getAddressForced() ? '*' : '';
?>
<div class="account-create">
    <div class="page-title">
        <h1><?php echo $this->__('Create an Account') ?></h1>
    </div>
    <?php echo $this->getChildHtml('form_fields_before')?>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php /* Extensions placeholder */ ?>
    <?php echo $this->getChildHtml('customer.form.register.extra')?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate">
		<div class="ui-content ">
			<div class="row">
				<div class="col-xs-12 acc-col">
					<?php echo $this->getBlockHtml('formkey'); ?>
					<div class="fieldset">
						<input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
						<input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
						<h3><?php echo $this->__('Personal Information') ?></h3>
						<?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
						<div class="customer-email-address row">
							<div class="field email-address col-md-8 col-xs-12">
								<label for="email_address" class="required control-label"><em>*</em><?php echo $this->__('Email Address') ?></label>
								<input type="text" name="email" id="email_address" value="<?php echo $this->escapeHtml($this->getFormData()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text form-control validate-email required-entry" />
							</div>
						</div>
						<?php if ($this->isNewsletterEnabled()): ?>
						<div class="row">
							<div class="field col-md-8 col-xs-12">
								<input type="checkbox" name="is_subscribed" title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1" id="is_subscribed"<?php if($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" />
								<label for="is_subscribed"><?php echo $this->__('Sign Up for Newsletter') ?></label>
							</div>
						</div>
						<?php /* Extensions placeholder */ ?>
						<?php echo $this->getChildHtml('customer.form.register.newsletter')?>
						<?php endif ?>
						<?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
						<?php if ($_dob->isEnabled()): ?>
							<?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?>
						<?php endif ?>
						<?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
						<?php if ($_taxvat->isEnabled()): ?>
							<?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?>
						<?php endif ?>
						<?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
						<?php if ($_gender->isEnabled()): ?>
							<?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?>
						<?php endif ?>
						
					</div>
				<?php if($this->getShowAddressFields()): ?>
					<div class="fieldset">
						<input id="create_address" type="hidden" name="create_address" value="1" />
						<h3><?php echo $this->__('Address Information') ?></h3>
						<ul class="row address-info">
							<li class="fields col-xs-12">
								<div class="row">
									<div class="field col-md-8 col-xs-12">
										<label for="company" class="control-label"><?php echo $this->__('Company') ?></label>
										<div class="input-box">
											<input type="text" name="company" id="company" value="<?php echo $this->escapeHtml($this->getFormData()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text form-control <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
										</div>
									</div>
									<div class="field col-md-4 col-xs-12">
										<label for="telephone" class="<?php echo $requiredClass ?> control-label"><em><?php echo $requiredCharacter ?></em><?php echo $this->__('Telephone') ?></label>
										<div class="input-box">
											<input type="text" name="telephone" id="telephone" value="<?php echo $this->escapeHtml($this->getFormData()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text form-control <?php echo $this->getAddressForced() ? $this->helper('customer/address')->getAttributeValidationClass('telephone') : ''?>" />
										</div>
									</div>
								</div>
							</li>
						<?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
							<li class="wide col-md-8 col-xs-12">
								<label for="street_1" class="<?php echo $requiredClass ?> control-label"><em><?php echo $requiredCharacter ?></em><?php echo $this->__('Street Address') ?></label>
								<div class="row">
									<div class="input-box col-md-6 col-xs-12">
										<input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet(1)) ?>" title="<?php echo $this->__('Street Address') ?>" id="street_1" class="input-text form-control create-address-indicator <?php echo $this->getAddressForced() ? $_streetValidationClass : ''?>" />
									</div>
						<?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
						<?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
									<div class="input-box col-md-6 col-xs-12">
										<input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet($_i)) ?>" title="<?php echo $this->__('Street Address %s', $_i) ?>" id="street_<?php echo $_i ?>" class="input-text form-control <?php echo $this->getAddressForced() ? $_streetValidationClass : '' ?>" />
									</div>
						<?php endfor; ?>
								</div>
							</li>
							<li class="fields col-md-4 col-xs-12">
								<div class="field">
									<label for="city" class="control-label <?php echo $requiredClass ?>"><em><?php echo $requiredCharacter ?></em><?php echo $this->__('City') ?></label>
									<div class="input-box">
										<input type="text" id="city" name="city" value="<?php echo $this->escapeHtml($this->getFormData()->getCity()) ?>" title="<?php echo $this->__('City') ?>" class="input-text form-control create-address-indicator <?php echo $this->getAddressForced() ? $this->helper('customer/address')->getAttributeValidationClass('city') : '' ?>" id="city" />
									</div>
								</div>
								<div class="field">
									<label for="region_id" class="control-label <?php echo $requiredClass ?>"><em><?php echo $requiredCharacter ?></em><?php echo $this->__('State/Province') ?></label>
									<div class="input-box">
										<select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="form-control validate-select" style="display:none;">
											<option value=""><?php echo $this->__('Please select region, state or province') ?></option>
										</select>
										<script type="text/javascript">
										//<![CDATA[
											$('region_id').setAttribute('defaultValue', "<?php echo $this->getFormData()->getRegionId() ?>");
										//]]>
										</script>
										<input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="form-control input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
									</div>
								</div>
							</li>
							<li class="fields col-md-4 col-xs-12">
								
								<?php if (!$this->getAddressForced()): ?>
								<div class="field col-md-4 col-xs-12 address-zipcode">
									<label for="zip" class="<?php echo $requiredClass ?> control-label"><em><?php echo $requiredCharacter ?></em><?php echo $this->__('Zip/Postal Code') ?></label>
									<div class="input-box">
										<input type="text" id="postcode" name="postcode" value="<?php echo $this->escapeHtml($this->getFormData()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="input-text form-control validate-zip-international create-address-indicator <?php echo $this->getAddressForced() ? $this->helper('customer/address')->getAttributeValidationClass('postcode') : ''?>" />
									</div>
								</div>
								<?php else: ?>
								<div class="field col-md-4 col-xs-12 address-zipcode">
									<label for="zip" class="required control-label"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
									<div class="input-box">
										<input type="text" name="postcode" value="<?php echo $this->escapeHtml($this->getFormData()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="input-text form-control validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
									</div>
								</div>
								<?php endif; ?>
								<div class="field address-country">
									<label for="country" class="<?php echo $requiredClass ?>"><em><?php echo $requiredCharacter ?></em><?php echo $this->__('Country') ?></label>
									<?php echo $this->getCountryHtmlSelect() ?>
								</div>
							</li>
						</ul>
						<input type="hidden" name="default_billing" value="1" />
						<input type="hidden" name="default_shipping" value="1" />
					</div>
				<?php endif; ?>
					<div class="fieldset">
						<h3><?php echo $this->__('Login Information') ?></h3>
						<ul class="row login-info">
							<li class="fields">
								<div class="field col-md-4 col-xs-12">
									<label for="password" class="required control-label"><em>*</em><?php echo $this->__('Password') ?></label>
									<div class="input-box">
										<input type="password" name="password" id="password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry form-control validate-password" />
									</div>
								</div>
								<div class="field col-md-4 col-xs-12">
									<label for="confirmation" class="required control-label"><em>*</em><?php echo $this->__('Confirm Password') ?></label>
									<div class="input-box">
										<input type="password" name="confirmation" title="<?php echo $this->__('Confirm Password') ?>" id="confirmation" class="input-text required-entry form-control validate-cpassword" />
									</div>
								</div>
							</li>
							<?php echo $this->getChildHtml('form.additional.info'); ?>
						</ul>
					</div>
					<div class="buttons-set">
						<p class="required"><?php echo $this->__('* Required Fields') ?></p>
						<div class="row">
							<p class="back-link col-sm-2 pull-left"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>" title="Back" class="back-link"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
							<div class="col-sm-4 pull-right">
								<button type="submit" title="<?php echo $this->__('Submit') ?>" class="button btn btn-success form-control"><span><span><?php echo $this->__('Submit') ?></span></span></button>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
        <?php if($this->getShowAddressFields()): ?>
        var _regionConfig = <?php echo $this->helper('directory')->getRegionJson(); ?>;

            <?php if (!$this->getAddressForced()): ?>
                _regionConfig.config.regions_required = [];
            <?php endif; ?>
        
        var ru = new RegionUpdater('country', 'region', 'region_id', _regionConfig, undefined, 'zip');
        <?php endif; ?>

        <?php if($this->getShowAddressFields() && !$this->getAddressForced()): ?>
        Event.observe(window, 'load', function() {
            initDsRegAddress();
        });

        function initDsRegAddress() {
            updateCreateAddress();
            $$('.create-address-indicator').each(function(e) {
                $(e.id).on('change', function() {
                    updateCreateAddress();
                });
            });
        }

        function updateCreateAddress(){
            if ($('postcode').value == '' && $('street_1').value == '' && $('city').value == '') {
                $('create_address').value = 0;
            } else {
                $('create_address').value = 1;
            }
        }
        <?php endif; //eof getShowAddressFields && !$this->getAddressForced() ?>
        
    //]]>
    </script>
</div>
