<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright  Copyright (c) 2012 Boost My Shop (http://www.boostmyshop.com)
 * @author : Nicolas MUGNIER
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @package MDN_MarketPlace
 * @version 2.1
 */
?>
<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?php echo $this->__('Edit Internationalization') ?></h3></td>
            <td class="a-right">
                <button onclick="history.back();" class="scalable back" type="button"><span><?php echo $this->__('Back') ?></span></button>
                <button onclick="formData.submit();" class="scalable save" type="button"><span><?php echo $this->__('Save') ?></span></button>
            </td>
        </tr>
    </table>
</div>

<div class="entry-edit">
    <fieldset>
        <form name="formData" id="formData" method="POST" action="<?php echo Mage::getUrl('MarketPlace/Internationalization/Save'); ?>">
            <input id="form_key" name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
            <input id="marketplace" name="marketplace" type="hidden" value="<?php echo $this->getMarketPlace()->getMarketPlaceName(); ?>" />
            <input id="store_id" name="store_id" type="hidden" value="<?php echo $this->getStore()->getId() ?>" />
            <table class="addproductPix_table">
                <tr>
                    <td width="200"><?php echo $this->__('Magento Store') ?></td>
                    <td><?php echo $this->getStore()->getname(); ?></td>
                </tr>
                <tr>
                    <td><?php echo $this->__('Association') ?></td>
                    <td><?php echo $this->getInternationalizationForm(); ?></td>
                </tr>
            </table>
        </form>
    </fieldset>
</div>