<div class="entry-edit">
    <div class="content-header">
        <table cellspacing="0" class="grid-header">
            <tr>
                <td><h3><?php echo $this->getTitle(); ?></h3></td>
                <td align="right">
                    <button onclick="setLocation('<?php echo $this->getBackUrl(); ?>');" class="scalable back" type="button"><span><?php echo $this->__('Back') ?></span></button>
                    <button onclick="document.location.href='<?php echo $this->getDeleteUrl() ?>'" class="scalable delete" type="button"><span><?php echo $this->__('Delete') ?></span></button>
                    <button onclick="ruleForm.submit();" class="scalable save" type="button"><span><?php echo $this->__('Save'); ?></span></button>
                </td>
            </tr>
        </table>
    </div>

    <form id="rule_form" method="POST" name="rule_form" action="<?php echo $this->getUrl("*/*/Save"); ?>">
        <div>
            <input type="hidden" id="form_key" name="form_key"  value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
            <input type="hidden" id="crr_id" name="crr_id"  value="<?php echo $this->getRule()->getId() ?>" />
        </div>
        <div id="ticket_fieldset" class="fieldset ">
            <div class="hor-scroll">
                <table class="form-list" cellspacing="0">
                    <tbody>
                        <tr>
                            <td class="label"><?php echo $this->__('Routing priority'); ?> <span class="required">*</span></td>
                            <td class="value">
                                <input class="input-text required-entry" type="text" name="rule[crr_priority]" id="crr_priority" value="<?php echo $this->getRule()->getcrr_priority(); ?>"></input>
                                <div class="tool-tip"><p>Enter a number from 0</p></div>

                            </td>
                        </tr>
                        <tr>
                            <td class="label"><?php echo $this->__('Ticket category'); ?></td>
                            <td class="value">
                                <?php
                                $block = $this->getLayout()->createBlock('CrmTicket/Admin_Category_Select');
                                $html = $block->getHtmlMenu($this->getRule()->getcrr_category(), 'rule[crr_category]', 'select', 0, null, true);
                                echo $html;
                                ?>
                            </td>
                        </tr>            
                        <?php if (Mage::helper('CrmTicket')->allowProductSelection()): ?>
                            <tr>
                                <td class="label"><?php echo $this->__('Product'); ?></td>
                                <td class="value">
                                    <select class="select" name="rule[crr_product]" id="crr_product">
                                        <option></option>
                                        <?php foreach ($this->getProducts() as $product) : ?>
                                            <option <?php if ($this->getRule()->getcrr_product() == $product->getId()) echo "selected" ?> value="<?php echo $product->getId(); ?>"><?php echo $product->getName(); ?></option>
                                        <?php endforeach; ?>    
                                    </select>
                                </td>
                            </tr>                        
                        <?php endif; ?>
                        <tr>
                            <td class="label"><?php echo $this->__('Store'); ?></td>
                            <td class="value">
                                <select name="rule[crr_store_id]" id="crr_store_id">
                                    <?php foreach ($this->getWebsiteCollection() as $website): ?>
                                        <optgroup label="<?php echo $website->getName(); ?>">
                                        <?php foreach ($this->getGroupCollection($website) as $group): ?>
                                            <?php if ($group->getWebsiteId() != $website->getId()) continue; ?>
                                            <optgroup label="&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $group->getName(); ?>">
                                            <?php foreach ($this->getStoreCollection($group) as $store): ?>
                                                <?php if ($store->getGroupId() != $group->getId()) continue; ?>
                                                    <option value="<? echo $store->getId(); ?>" <?php echo ($this->getRule()->getcrr_store_id() == $store->getId() ? ' selected="selected"' : ''); ?>>&nbsp;&nbsp;&nbsp;&nbsp; <?php echo $store->getName(); ?></option>
                                            <?php endforeach; ?>
                                            </optgroup>
                                        <?php endforeach; ?>
                                        </optgroup>
                                    <?php endforeach; ?>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td class="label"><?php echo $this->__('Manager'); ?> <span class="required">*</span></td>
                            <td class="value">
                                <select class="required-entry select" name="rule[crr_manager]" id="crr_manager">
                                    <?php foreach ($this->getManagers() as $manager) : ?>
                                        <option <?php if ($this->getRule()->getcrr_manager() == $manager->getId()) echo "selected" ?> value="<?php echo $manager->getId(); ?>"><?php echo $manager->getUsername(); ?></option>
                                    <?php endforeach; ?>    
                                </select>
                            </td>
                        </tr>                        
                    </tbody>
                </table>
            </div>
        </div>

    </form>
    <script type="text/javascript">
        ruleForm = new varienForm('rule_form', '');
    </script> 



</div>

