<div class="entry-edit" >
    <div class="content-header">
        <table cellspacing="0" class="grid-header">
            <tr>
                <td><h3><?php echo $this->__('Tickets'); ?></h3></td>
            </tr>            
        </table>
    </div>

    <!-- Enable the tooptip to don't be cutted by the grid that have by default overflow: hidden; -->
    <style>.hor-scroll {overflow: inherit !important; }</style>

    <?php echo $this->getGridParentHtml(); ?>
</div>