<p>Use our 3 step cartridge finder to locate supplies for your printer</p>
<?php $baseUrl = Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true ); ?>
<p><?php $filter = new Mage_Widget_Model_Template_Filter();
$_widget = $filter->filter('{{widget type="tonerconfigurator/configurator" title="Find Neopost Cartridges" styling="default" search_text="Search" loading_text="Loading Category Information..."}}');
echo $_widget; ?></p>
<p>Or choose your printer from the list below</p><table width="100%" border="0"><tr><td colspan="4">&nbsp;</td></tr>
<tr style="border-top: solid;"><td colspan="4">&nbsp;<br /><font style="font-size: 25px;"><strong>Neopost IJ</strong></font><br />&nbsp;</td></tr><td width="25%"><a href="<?php echo $baseUrl ?>catalog/category/view/s/ij-25/id/14065">Neopost IJ 25</a></td></tr><tr><tr><td colspan="4">&nbsp;</td></tr>
<tr style="border-top: solid;"><td colspan="4">&nbsp;<br /><font style="font-size: 25px;"><strong>Neopost Other</strong></font><br />&nbsp;</td></tr><tr><td width="25%"><a href="<?php echo $baseUrl ?>catalog/category/view/s/ijx-25/id/14077">Neopost IJX 25</a></td><td width="25%"><a href="<?php echo $baseUrl ?>catalog/category/view/s/msl-250/id/14071">Neopost MSL 250</a></td><td colspan="2">&nbsp;</td></tr></table><br /><a href="/pl"><strong>Back to Manufacturer List</strong></a>