<?php
$old	=date_default_timezone_get();
date_default_timezone_set('Europe/London');
$time	=date("H");
$day	=date("D");
echo $time." on ".$day;
if($day=="Sat" || $day=="Sun") {
 // It is Saturday or Sunday. Return Tuesday.
 $display=date('l jS F', strtotime(date("Y-m-d").' +2 Weekday'));
}
elseif($time>="17" && $day=="Fri") {
 // It's a Friday after 17:00. Return Tuesday.
 $display=date('l jS F', strtotime(date("Y-m-d").' +2 Weekday'));
}
elseif($time<"17" && $day=="Fri") {
 // It's a Friday before 17:00. Return Monday.
 $display=date('l jS F', strtotime(date("Y-m-d").' +1 Weekday'));
}
elseif($time>"17") {
 // It is a weekday after 17:00. Return +2 days.
 $display=date('l jS F', strtotime(date("Y-m-d").' +2 Weekday'));
}
else {
 // It is a weekday before 17:00. Return +1 day.
 $display=date('l jS F', strtotime(date("Y-m-d").' +1 Weekday'));
}
date_default_timezone_set($old);

echo "\r\n".date("H")." on ".date("D");
