<?php
/**
 * OneStepCheckout
 * 
 * NOTICE OF LICENSE
 *
 * This source file is subject to One Step Checkout AS software license.
 *
 * License is available through the world-wide-web at this URL:
 * https://www.onestepcheckout.com/LICENSE.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to mail@onestepcheckout.com so we can send you a copy immediately.
 *
 * @category   Idev
 * @package    Idev_OneStepCheckout
 * @copyright  Copyright (c) 2009 OneStepCheckout  (https://www.onestepcheckout.com/)
 * @license    https://www.onestepcheckout.com/LICENSE.txt
 */
?>
<div class="page-title">
    <h1><?php echo $this->__('Create an Account') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('onestepcheckout/ajax/register') ?>" method="post" id="form-validate" class="register-form">
    <div class="fieldset">
        <h4 class="legend"><?php echo $this->__('Enter your password') ?></h4>
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label class="required" for="password"><em>*</em><?php echo $this->__('Password') ?></label>
                    <div class="input-box">
                        <input type="password" name="password" id="password" title="<?php echo $this->__('Password') ?>" class="required-entry validate-password input-text" />
                    </div>
                </div>
                   <div class="field">
                    <label class="required" for="confirmation"><em>*</em><?php echo $this->__('Confirm Password') ?></label>
                    <div class="input-box">
                        <input type="password" name="confirmation" title="<?php echo $this->__('Confirm Password') ?>" id="confirmation" class="required-entry validate-cpassword input-text" />
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <button id="create-account-button" class="button" type="submit"><span><span><?php echo $this->__('Submit') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    //var dataForm = new VarienForm('form-validate', true);
    <?php if($this->getShowAddressFields()): ?>
    new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>);
    <?php endif; ?>

    Translator.add('Please check your inbox for registration confirmation e-mail.','<?php echo $this->__('Please check your inbox for registration confirmation e-mail.')?>');

    $('create-account-button').observe('click', function(e)    {

        Event.stop(e);

        var url = '<?php echo $this->getUrl('onestepcheckout/ajax/register', array('_secure'=>true)); ?>';
        var parameters = $$('form.register-form').first().serialize(true);

        new Ajax.Request(url, {
                method: 'post',
                parameters: parameters,
                onComplete: function(response)  {
                    if(response.status == 200)  {
                         var result = response.responseText.evalJSON();

                         if(result.success && result.message == 'customer_logged_in')   {
                             window.location='<?php echo $this->getUrl('customer/account', array('_secure'=>true)); ?>';
                         } else if(result.success && result.message == 'email_confirmation')   {
                             alert('<?php echo $this->__('Please check your inbox for registration confirmation e-mail.')?>');
                             window.location='<?php echo $this->getUrl('customer/account', array('_secure'=>true)); ?>';
                         } else  {
                            alert('Error occured: ' + result.error);
                         }
                    }
                }
        });
    });
//]]>
</script>
