<div class="discount">

    <h2><?php echo $this->__('Discount Codes') ?></h2>
    
    <form id="discount-coupon-form" action="<?php echo $this->getUrl('checkout/cart/couponPost') ?>" method="post">
    <div class="discount-form">
        <label for="coupon_code"><?php echo $this->__('Enter your voucher code if you have any.') ?></label>
        <input type="hidden" name="remove" id="remove-coupone" value="0" />
        <div class="input-box">
            <input class="input-text" id="coupon_code" name="coupon_code" value="" />
        </div>
        <div class="buttons-set">
            <button type="button" title="<?php echo $this->__('Apply Voucher') ?>" class="button" onclick="discountForm.submit(false)" value="<?php echo $this->__('Apply Coupon') ?>"><span><span><?php echo $this->__('Apply Coupon') ?></span></span></button>
        </div>
    </div>
    </form>
    
    
    <?php if ($this->getAppliedCoupons()): ?>
    <br />
        <h2><?php echo $this->__('Applied Vouchers'); ?></h2>
        
        <table border="0" width="100%" cellpadding="4" cellspacing="0" style="padding-top: 3px;">
        
        <?php $couponCnt = 0; ?>
        <?php foreach ($this->getAppliedCoupons() as $coupon): ?>
            <tr style="padding-bottom: 3px;">
                <td><?php echo $coupon; ?></td>
                <td style="text-align: right;">
                    <form id="discount-coupon-cancel-form-<?php echo $couponCnt; ?>" action="<?php echo $this->getUrl('amcoupons/checkout/cancelCoupon') ?>" method="post">
                        <input type="hidden" name="amcoupon_code_cancel" value="<?php echo $coupon; ?>" />
                        <a href="#" onclick="javascript: $('discount-coupon-cancel-form-<?php echo $couponCnt; ?>').submit(); return false;"><?php echo $this->__('Cancel'); ?></a>
                    </form>
                </td>
            </tr>
            <?php $couponCnt++; ?>
        <?php endforeach; ?>
        </table>
    <?php endif; ?>
    
    
</div>

<script type="text/javascript">
//<![CDATA[
var discountForm = new VarienForm('discount-coupon-form');
discountForm.submit = function (isRemove) {
    if (isRemove) {
        $('coupon_code').removeClassName('required-entry');
        $('remove-coupone').value = "1";
    } else {
        $('coupon_code').addClassName('required-entry');
        $('remove-coupone').value = "0";
    }
    return VarienForm.prototype.submit.bind(discountForm)();
}
//]]>
</script>
