<table cellpadding="5" cellspacing="0" border="0" width="100%" style="color:#000000;font-family:Arial, Helvetica, sans-serif;font-size:12px;border:0px none transparent;">
    <tr>
        <td align="left" valign="top" width="34%">
            <table width="100%" cellpadding="0" cellspacing="0" border="0" style="color:#000000;font-family:Arial, Helvetica, sans-serif;font-size:12px;">
                <tr>
                    <td>
                        <div align="left">
                            <img src="[BasketItem:Custom.product_img_url]" border="0" style="display:block">
                        </div>
                    </td>
                </tr>
            </table>
        </td>
        <td align="left" valign="top" width="40%">
            <table cellpadding="0" cellspacing="0" border="0" width="100%" style="color:#000000;font-family:Arial, Helvetica, sans-serif;font-size:12px;">
                <tr>
                    <td valign="top">
                        <div style="text-align: left;">
                            <b>[BasketItem:Name]</b>
                            <br><br>
                            [BasketItem:Description]
                        </div>
                    </td>
                </tr>
            </table>
        </td>
        <td align="left" valign="top" width="26%">
            <table cellpadding="0" cellspacing="0" border="0" width="100%" style="color:#000000;font-family:Arial, Helvetica, sans-serif;font-size:12px;">
                <tr>
                    <td valign="top" style="font-size:12px;">&nbsp;</td>
                </tr>
            </table>
            <table cellpadding="0" cellspacing="0" border="0" width="100%" style="color:#000000;font-family:Arial, Helvetica, sans-serif;font-size:12px;">
                <tr>
                    <td valign="top" style="font-size:12px;">&nbsp;</td>
                </tr>
            </table>
            <table cellpadding="0" cellspacing="0" border="0" width="100%" style="color:#000000;font-family:Arial, Helvetica, sans-serif;font-size:12px;">
                <tr>
                    <td valign="top">
                        <table cellpadding="0" cellspacing="5" border="0" align="left" style="color:#FFFFFF;font-family:Arial, Helvetica, sans-serif;font-size:16px;border:5px solid #999999;background-color:#999999;">
                            <tr>
                                <td align="center" valign="top">
                                    <div>
                                        <span style="font-size: 14px;">
                                            <b><a href="[BasketItem:Custom.product_url]" target="_blank"  style="text-decoration:none;color:#FFFFFF;">View in Store</a></b>
                                        </span>
                                    </div>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>