<?php
    $_helper = $this->helper('catalog/output');
    $_product = $this->getProduct();
?>
<ul class="messages ap-dialog-messages">
	<li class="success-msg ap-dialog-success-message">
		<span><?php echo $this->__('%s was added to your compare list.', $this->getProduct()->getName()); ?></span>
	</li>
</ul>
<div class="product-shop">
	<div class="product-img-box" style="float: left; margin: 0px 10px 0px 0px">
		<?php
	        $_img = '<img id="image" src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(55).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'"/>';
	       echo $_helper->productAttribute($_product, $_img, 'image');
	    ?>
	</div>
	<div class="product-name">
		<h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
		<p class="availability in-stock">Availability: <span>In stock</span></p>
	</div>
</div>	
<div style="text-align: center; margin-top: 15px;">
	<button class="button ap-dialog-button" type="button" onclick="ewcart.close();"><span><span><?php echo $this->__('Continue Shopping'); ?></span></span></button>
	<br><br>
	<button class="button ap-dialog-button" type="button" onclick="popWin('<?php echo Mage::helper('catalog/product_compare')->getListUrl(); ?>','compare','width=800,height=600,resizable=yes,scrollbars=yes'); ewcart.close();"><span><span><?php echo $this->__('Compare Products'); ?></span></span></button>
</div>
<script type="text/javascript">    
//<![CDATA[
<?php if ((int)$this->mHelper('config')->getDialogDisplayTime() > 0):?>
ewcart.close(<?php echo (int)$this->mHelper('config')->getDialogDisplayTime(); ?>);
<?php endif; ?>
<?php
	$_javascript = $this->getJavascript();
	foreach ($_javascript as $_js) {
		echo "{$_js}\n";
	}
?>
ewcart.rewritePage();
//]]>
</script>
