<p>Use our 3 step cartridge finder to locate supplies for your printer</p>
<p><?php $filter = new Mage_Widget_Model_Template_Filter();
$_widget = $filter->filter('{{widget type="tonerconfigurator/configurator" title="Find A 10 Cartridges" styling="default" button_based="1" search_text="Search" loading_text="Loading Category Information..."}}');
echo $_widget; ?></p>
<p>Or choose your printer from the list below</p><table width="100%" border="0"><td colspan="4">&nbsp;</td></tr></table><br /><a href="/pl"><strong>Back to Manufacturer List</strong></a>