<p>Use our 3 step cartridge finder to locate supplies for your printer</p>
<p><?php $filter = new Mage_Widget_Model_Template_Filter();
$_widget = $filter->filter('{{widget type="tonerconfigurator/configurator" title="Find Medion Cartridges" styling="default" button_based="1" search_text="Search" loading_text="Loading Category Information..."}}');
echo $_widget; ?></p>
<p>Or choose your printer from the list below</p><table width="100%" border="0"></tr><tr><tr><td colspan="4">&nbsp;</td></tr>
<tr style="border-top: solid;"><td colspan="4">&nbsp;<br /><font style="font-size: 25px;"><strong>Medion Other</strong></font><br />&nbsp;</td></tr><tr><td width="25%"><a href="http://www.choicestationery.com/catalog/category/view/s/md-9990/id/">Medion MD 9990</a></td><td colspan="3">&nbsp;</td></tr></table><br /><a href="/pl"><strong>Back to Manufacturer List</strong></a>